/*
 * File: app/model/Customer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CRUD.model.Customer', {
    extend: 'Ext.data.Model',
    alias: 'model.customer',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id',
            type: 'integer'
        },
        {
            name: 'firstName',
            type: 'string'
        },
        {
            name: 'lastName',
            type: 'string'
        },
        {
            name: 'isPremium',
            type: 'boolean'
        },
        {
            name: 'totalPurchases',
            type: 'float'
        },
        {
            name: 'email',
            type: 'string'
        },
        {
            name: 'phone',
            type: 'string'
        },
        {
            name: 'signupDate',
            type: 'date'
        },
        {
            name: 'streetAddress',
            type: 'string'
        },
        {
            name: 'city',
            type: 'string'
        },
        {
            name: 'state',
            type: 'string'
        },
        {
            name: 'zip',
            type: 'string'
        },
        {
            name: 'country',
            type: 'string'
        },
        {
            name: 'comments',
            type: 'string'
        }
    ]
});